# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: niteshnk16
app: serverless-user-management
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-user-management-api

provider:
  name: aws
  runtime: python3.12
  region: us-east-2  
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: get

  bye:
    handler: handler.bye
    events:
      - httpApi:
          path: /bye
          method: get

